# Generated by Django 3.2.9 on 2021-11-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='address',
        ),
        migrations.AddField(
            model_name='screening',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theatre',
            name='city',
            field=models.CharField(choices=[('DELHI', 'Delhi'), ('KOLKATA', 'Kolkata'), ('MUMBAI', 'Mumbai'), ('CHENNAI', 'Chennai'), ('BANGALORE', 'Bangalore'), ('HYDERABAD', 'Hyderabad')], default='', editable=False, max_length=9),
        ),
        migrations.AlterField(
            model_name='movie',
            name='certification_label',
            field=models.CharField(choices=[('U', 'U'), ('UA', 'U/A'), ('A', 'A'), ('R', 'R')], max_length=2),
        ),
    ]
