# Generated by Django 3.2.9 on 2021-11-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_theatre_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
    ]
