# Generated by Django 3.2.9 on 2021-11-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_screening_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
