# Generated by Django 3.2.9 on 2021-11-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_screening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='movie_pics'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(default='https://www.youtube.com/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='certification_label',
            field=models.CharField(choices=[('U', 'U'), ('UA', 'UA'), ('A', 'A'), ('S', 'S')], max_length=2),
        ),
    ]
