# Generated by Django 3.2.9 on 2021-11-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20211125_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='movie_pics'),
        ),
    ]
