# Generated by Django 3.2.9 on 2021-11-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0002_ticket_no_of_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
