# Generated by Django 3.2.9 on 2021-11-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0004_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
