# Generated by Django 3.2.9 on 2021-11-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0005_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booking_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
